language: node_js
node_js:
  - node

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools ionic

script:
  - ionic build --prod  

after_success:
  - firebase deploy --token ${FIREBASE_TOKEN}  --only hosting

notifications:
  email:
    - thomazrdamasceno@gmail.com
   