language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - ionic build --prod  

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}

  notifications:
  email:
    on_failure: thomazrdamasceno@gmail.com
    on_success: thomazrdamasceno@gmail.com